name: CI

on:
  push:
    branches: [ master ]

env: 
  BUCKET: appreactregister

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - uses: GoogleCloudPlataform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT }}
          service_account_key: ${{ secrets.KEY_SA }}
          export_default_credentials: true
          
      - name: Upload filed to bucket
        run: gsutil -m rsync -R ./build gs://"$BUCKET"
      
      - name: Allow public access
        run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"
      
      - name: Set Cache-Controll
        run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/**/*.{png,svg,css,js}
        
      - name: Set Cache-Control
        run: gsutil setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html

     
